apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: query-hpa
  namespace: tracking-system
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: query
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          # škáluj nahoru pokud průměrné CPU přes všechny query pody překročí 70% requestu (50m)
          averageUtilization: 70