apiVersion: v1
kind: Service
metadata:
  name: ingest-service
  namespace: tracking-system
  labels:
    app: ingest
spec:
  selector:
    app: ingest
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
      name: grpc
    - protocol: TCP
      port: 9090
      targetPort: 9090
      name: metrics