apiVersion: v1
kind: Service
metadata:
  name: processor-service
  namespace: tracking-system
spec:
  selector:
    app: processor
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      name: metrics