apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tracking-ingest
  namespace: tracking-system
  labels:
    # Prometheus Operator hledá ServiceMonitory s labelem release=kube-prometheus-stack
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: ingest
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tracking-processor
  namespace: tracking-system
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: processor
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tracking-query
  namespace: tracking-system
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: query
  endpoints:
    - port: http
      path: /metrics
      interval: 15s