apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulator
  namespace: tracking-system
  labels:
    app: simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulator
  template:
    metadata:
      labels:
        app: simulator
    spec:
      containers:
        - name: simulator
          image: ghcr.io/bojkoj/simulator:6146430
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: tracking-config
            - secretRef:
                name: tracking-secret
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi